### ISSUE TITLE
Reuse derivative rules from Calculus?

### ISSUE THREAD

**Issue by mlubin** [LaurenceA/ReverseDiffOverload.jl#1]
In DualNumbers, we've reused the derivative rules from Calculus: https://github.com/scidom/DualNumbers.jl/blob/master/src/dual.jl#L161. Is that possible here?

**Comment by LaurenceA** [comment]
Probably.  My only worry is that the rules here:

https://github.com/johnmyleswhite/Calculus.jl/blob/master/src/differentiate.jl

Won't take vector inputs (i.e. they use `*` rather than `.*` everywhere).  I'd be happy to change the rules - but I'm not quite sure how to start, given the sensitivity of the code (e.g. open an issue there?).

**Comment by mlubin** [comment]
I was thinking just the `derivative_rules` list which has scalar functions, not operators like `*`, `+`, `^`, etc. Would these work?

**Comment by LaurenceA** [comment]
My worry is that, as you say, the functions in `derivative_rules` only take scalars.  They could be extended to take vectors by, for instance, replacing `*` with `.*` in all the rules.

**Comment by LaurenceA** [comment]
Done

**Comment by mlubin** [comment]
Cool!
